CREATE TABLE "futures_submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" integer NOT NULL,
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"project_name" varchar(255),
	"project_type" varchar(100),
	"expected_annual_generation" numeric(14, 3),
	"expected_completion_date" varchar(10),
	"dev_license_doc_url" varchar(500),
	"dev_license_doc_type" varchar(255),
	"dev_license_llm_match" boolean,
	"dev_license_llm_reason" text,
	"land_rights_doc_url" varchar(500),
	"land_rights_doc_type" varchar(255),
	"land_rights_llm_match" boolean,
	"land_rights_llm_reason" text,
	"equip_procurement_doc_url" varchar(500),
	"equip_procurement_doc_type" varchar(255),
	"equip_procurement_llm_match" boolean,
	"equip_procurement_llm_reason" text,
	"proj_timeline_doc_url" varchar(500),
	"proj_timeline_doc_type" varchar(255),
	"proj_timeline_llm_match" boolean,
	"proj_timeline_llm_reason" text,
	"eng_specs_doc_url" varchar(500),
	"eng_specs_doc_type" varchar(255),
	"eng_specs_llm_match" boolean,
	"eng_specs_llm_reason" text,
	"funding_commitment_doc_url" varchar(500),
	"funding_commitment_doc_type" varchar(255),
	"funding_commitment_llm_match" boolean,
	"funding_commitment_llm_reason" text,
	"grid_connection_doc_url" varchar(500),
	"grid_connection_doc_type" varchar(255),
	"grid_connection_llm_match" boolean,
	"grid_connection_llm_reason" text,
	"review_notes" text,
	"reviewed_at" timestamp,
	"reviewed_by" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "futures_submissions_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "goals" (
	"id" serial PRIMARY KEY NOT NULL,
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"company_wallet" varchar(42) NOT NULL,
	"scope" integer NOT NULL,
	"target_mwh" numeric(14, 3),
	"target_tco2e" numeric(14, 3),
	"description" text,
	"target_year" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "goals_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "onboarding_submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" integer NOT NULL,
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"project_name" varchar(255),
	"project_type" varchar(100),
	"expected_annual_generation" numeric(14, 3),
	"gen_generation_type" varchar(50),
	"gen_doc_url" varchar(500),
	"gen_doc_type" varchar(255),
	"gen_secondary_src" varchar(100),
	"gen_secondary_desc" varchar(500),
	"gen_tertiary_src" varchar(100),
	"gen_tertiary_desc" varchar(500),
	"gen_llm_doc_type_match" boolean,
	"gen_llm_content_match" boolean,
	"gen_llm_reason" text,
	"cap_capacity" numeric(14, 3),
	"cap_doc_url" varchar(500),
	"cap_doc_type" varchar(255),
	"cap_llm_doc_type_match" boolean,
	"cap_llm_content_match" boolean,
	"cap_llm_reason" text,
	"loc_physical_address" varchar(500),
	"loc_lat" double precision,
	"loc_lon" double precision,
	"loc_doc_url" varchar(500),
	"loc_doc_type" varchar(255),
	"loc_llm_doc_type_match" boolean,
	"loc_llm_content_match" boolean,
	"loc_llm_reason" text,
	"date_date_of_first_operation" varchar(10),
	"date_doc_url" varchar(500),
	"date_doc_type" varchar(255),
	"date_llm_doc_type_match" boolean,
	"date_llm_content_match" boolean,
	"date_llm_reason" text,
	"photos_gen" jsonb,
	"photos_gen_llm_match" boolean,
	"photos_gen_llm_reason" text,
	"photos_meter" jsonb,
	"photos_meter_llm_match" boolean,
	"photos_meter_llm_reason" text,
	"review_notes" text,
	"reviewed_at" timestamp,
	"reviewed_by" integer,
	"admin_edited_at" timestamp,
	"admin_edited_by" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "onboarding_submissions_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" integer NOT NULL,
	"company_wallet" varchar(42) NOT NULL,
	"contract_address" varchar(42),
	"contract_name" varchar(100),
	"abbreviation" varchar(20),
	"side" varchar(6) NOT NULL,
	"order_type" varchar(20) NOT NULL,
	"amount" integer NOT NULL,
	"limit_price" numeric(12, 4),
	"stop_price" numeric(12, 4),
	"notes" text,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"processed_at" timestamp,
	"processed_by" integer,
	"processing_notes" text,
	CONSTRAINT "orders_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"is_generator" boolean DEFAULT false NOT NULL,
	"is_buyer" boolean DEFAULT false NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"company_wallet" varchar(42),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"created_by" integer,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "futures_submissions" ADD CONSTRAINT "futures_submissions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "futures_submissions" ADD CONSTRAINT "futures_submissions_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "onboarding_submissions" ADD CONSTRAINT "onboarding_submissions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "onboarding_submissions" ADD CONSTRAINT "onboarding_submissions_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "onboarding_submissions" ADD CONSTRAINT "onboarding_submissions_admin_edited_by_users_id_fk" FOREIGN KEY ("admin_edited_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_processed_by_users_id_fk" FOREIGN KEY ("processed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;