[profile.default]
etherscan_api_key = "${ETHERSCAN_API_KEY}"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
	"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
polygon = "https://polygon.drpc.org"